use document_tracking_system;
insert into doc_code_list values
(1, 'CDCR', 'Cashier\'s Daily Collection Report'),
(2, 'OR', 'Official Receipt'),
(3, 'SBACR', 'SBA Collection Report'),
(4, 'BCCR', 'Bayad Center Collection Report'),
(5, 'RV', 'Requisition Voucher'),
(6, 'Abs', 'Abstract'),
(7, 'PO', 'Purchase Order'),
(8, 'IOT', 'Itinerary of Travel'),
(9, 'LOT', 'Liquidation of Travel'),
(10, 'LOCAH', 'Liquidation of Cash Advance-Hospitalization'),
(11, 'LOCAMSP', 'Liquidation of Cash Advance-Motorpool Spare Parts'),
(12, 'LOCA', 'Liquidation of Cash Advance'),
(13, 'ROOE', 'Reimbursement of Other Expenses'),
(14, 'ROME', 'Reimbursement of Medical Expenses'),
(15, 'PCR', 'Petty Cash Replenishment'),
(16, 'SOA', 'Statement of Account'),
(17, 'NEA', 'NEA com'),
(18, 'ERC', 'ERC com'),
(19, 'PS', 'Power Supply com'),
(20, 'REPAY', 'Regular EE Payroll'),
(21, 'CEPAY', 'Contractual EE Payroll'),
(22, 'EWT', 'Employees Withholding Tax'),
(23, 'IAR', 'Internal Audit Reports'),
(24, 'BRS', 'Bank Reconciliation Statement'),
(25, 'CV', 'Check Voucher'),
(26, 'ROE', 'Reimbursement of Expenses');